name: robomimic_venv
channels:
  - pyg
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.4.3
  - aiohttp=3.11.11
  - aiosignal=1.3.1
  - alsa-lib=1.2.8
  - aom=3.5.0
  - async-timeout=4.0.3
  - attr=2.5.1
  - attrs=24.2.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.1.31
  - cairo=1.16.0
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - colorama=0.4.6
  - contourpy=1.3.1
  - cuda-version=11.6
  - cudatoolkit=11.6.2
  - cudnn=8.9.7.29
  - cycler=0.12.1
  - dbus=1.13.6
  - einops=0.8.1
  - expat=2.6.4
  - ffmpeg=5.1.2
  - fftw=3.3.10
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.55.8
  - freeglut=3.2.2
  - freetype=2.12.1
  - frozenlist=1.5.0
  - fsspec=2024.10.0
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - glib=2.82.2
  - glib-tools=2.82.2
  - gmp=6.3.0
  - gnutls=3.7.9
  - graphite2=1.3.13
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - gstreamer-orc=0.4.40
  - h2=4.1.0
  - harfbuzz=6.0.0
  - hdf5=1.14.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=70.1
  - idna=3.10
  - jack=1.9.22
  - jasper=2.0.33
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.67
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcups=2.3.3
  - libcurl=8.1.2
  - libdb=6.2.32
  - libdeflate=1.17
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.6.4
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt=1.11.0
  - libgcrypt-devel=1.11.0
  - libgcrypt-lib=1.11.0
  - libgcrypt-tools=1.11.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.82.2
  - libglu=9.0.0
  - libgomp=14.2.0
  - libgpg-error=1.51
  - libhwloc=2.9.1
  - libiconv=1.17
  - libidn2=2.3.7
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm15=15.0.7
  - liblzma=5.6.3
  - liblzma-devel=5.6.3
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libogg=1.3.5
  - libopenblas=0.3.25
  - libopencv=4.7.0
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.45
  - libpq=15.3
  - libprotobuf=3.21.12
  - libsndfile=1.2.2
  - libsqlite=3.48.0
  - libssh2=1.11.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=253
  - libtasn1=4.20.0
  - libtiff=4.5.0
  - libtool=2.4.7
  - libudev1=253
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.18.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp-base=1.5.0
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libzlib=1.3.1
  - llvm-openmp=19.1.7
  - lz4-c=1.9.4
  - magma=2.5.4
  - markupsafe=3.0.2
  - matplotlib=3.9.1
  - matplotlib-base=3.9.1
  - mkl=2022.2.1
  - mpg123=1.32.9
  - multidict=6.1.0
  - munkres=1.1.4
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - nccl=2.24.3.1
  - ncurses=6.5
  - nettle=3.9.1
  - networkx=3.1
  - ninja=1.12.1
  - nspr=4.36
  - nss=3.107
  - opencv=4.7.0
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.1.8
  - p11-kit=0.24.1
  - packaging=24.2
  - pcre2=10.44
  - pillow=9.4.0
  - pip=24.3.1
  - pixman=0.44.2
  - platformdirs=4.3.6
  - ply=3.11
  - pooch=1.8.2
  - propcache=0.2.1
  - protobuf=4.21.12
  - psutil=6.1.1
  - pthread-stubs=0.4
  - pulseaudio=16.1
  - pulseaudio-client=16.1
  - pulseaudio-daemon=16.1
  - py-opencv=4.7.0
  - pycparser=2.22
  - pyg=2.5.2
  - pyparsing=3.1.4
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pytorch=1.12.1
  - qhull=2020.2
  - qt-main=5.15.8
  - readline=8.2
  - requests=2.32.3
  - scikit-learn=1.6.1
  - scipy=1.15.1
  - setuptools=75.3.0
  - sip=6.7.12
  - six=1.17.0
  - sleef=3.7
  - sqlite=3.48.0
  - svt-av1=1.4.1
  - tbb=2021.9.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.2.1
  - torchvision=0.13.0
  - tornado=6.4.2
  - tqdm=4.67.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - unicodedata2=16.0.0
  - urllib3=2.2.3
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.6.3
  - xz-gpl-tools=5.6.3
  - xz-tools=5.6.3
  - yarl=1.18.3
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - arm-pytorch-utilities==0.4.3
      - beautifulsoup4==4.13.3
      - chardet==5.2.0
      - click==8.1.8
      - egl-probe==1.0.2
      - etils==1.11.0
      - evdev==1.8.0
      - filelock==3.17.0
      - gdown==5.2.0
      - glfw==2.8.0
      - grpcio==1.70.0
      - h5py==3.12.1
      - huggingface-hub==0.29.1
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-resources==6.5.2
      - iniconfig==2.0.0
      - llvmlite==0.44.0
      - lxml==5.3.0
      - markdown==3.7
      - mink==0.0.5
      - mujoco==3.2.7
      - numba==0.61.0
      - numpy
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - opencv-python-headless==4.11.0.86
      - pluggy==1.5.0
      - pynput==1.7.7
      - pyopengl==3.1.9
      - pytest==8.3.4
      - python-xlib==0.33
      - pytorch-kinematics==0.7.5
      - pytorch-seed==0.2.0
      - pyyaml==6.0.2
      - qpsolvers==4.4.0
      - quadprog==0.1.13
      - robosuite==1.5.1
      - soupsieve==2.6
      - sympy==1.13.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - termcolor==2.5.0
      - torch==2.6.0
      - torchaudio==2.6.0+cu126
      - triton==3.2.0
      - werkzeug==3.1.3
      - zipp==3.21.0
